// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SellersUsersServiceClient is the client API for SellersUsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellersUsersServiceClient interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	AccoundData(ctx context.Context, in *AccountDataRequest, opts ...grpc.CallOption) (*AccountDataResponse, error)
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
}

type sellersUsersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSellersUsersServiceClient(cc grpc.ClientConnInterface) SellersUsersServiceClient {
	return &sellersUsersServiceClient{cc}
}

func (c *sellersUsersServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/protobuf.SellersUsersService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellersUsersServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/protobuf.SellersUsersService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellersUsersServiceClient) AccoundData(ctx context.Context, in *AccountDataRequest, opts ...grpc.CallOption) (*AccountDataResponse, error) {
	out := new(AccountDataResponse)
	err := c.cc.Invoke(ctx, "/protobuf.SellersUsersService/AccoundData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellersUsersServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, "/protobuf.SellersUsersService/CheckAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellersUsersServiceServer is the server API for SellersUsersService service.
// All implementations must embed UnimplementedSellersUsersServiceServer
// for forward compatibility
type SellersUsersServiceServer interface {
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	AccoundData(context.Context, *AccountDataRequest) (*AccountDataResponse, error)
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
	mustEmbedUnimplementedSellersUsersServiceServer()
}

// UnimplementedSellersUsersServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSellersUsersServiceServer struct {
}

func (UnimplementedSellersUsersServiceServer) SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (UnimplementedSellersUsersServiceServer) SignIn(context.Context, *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedSellersUsersServiceServer) AccoundData(context.Context, *AccountDataRequest) (*AccountDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccoundData not implemented")
}
func (UnimplementedSellersUsersServiceServer) CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedSellersUsersServiceServer) mustEmbedUnimplementedSellersUsersServiceServer() {}

// UnsafeSellersUsersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellersUsersServiceServer will
// result in compilation errors.
type UnsafeSellersUsersServiceServer interface {
	mustEmbedUnimplementedSellersUsersServiceServer()
}

func RegisterSellersUsersServiceServer(s grpc.ServiceRegistrar, srv SellersUsersServiceServer) {
	s.RegisterService(&SellersUsersService_ServiceDesc, srv)
}

func _SellersUsersService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellersUsersServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SellersUsersService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellersUsersServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellersUsersService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellersUsersServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SellersUsersService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellersUsersServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellersUsersService_AccoundData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellersUsersServiceServer).AccoundData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SellersUsersService/AccoundData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellersUsersServiceServer).AccoundData(ctx, req.(*AccountDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellersUsersService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellersUsersServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SellersUsersService/CheckAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellersUsersServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SellersUsersService_ServiceDesc is the grpc.ServiceDesc for SellersUsersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellersUsersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.SellersUsersService",
	HandlerType: (*SellersUsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _SellersUsersService_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _SellersUsersService_SignIn_Handler,
		},
		{
			MethodName: "AccoundData",
			Handler:    _SellersUsersService_AccoundData_Handler,
		},
		{
			MethodName: "CheckAccess",
			Handler:    _SellersUsersService_CheckAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sellers_users_service.proto",
}
